"""Patch builder — creates the final installable patch for distribution.

Creates a diff-based patch that applies to a legitimate copy of the game.
The patch contains ONLY modified files (translated SCX, font, images) —
never the original game assets.

Output: SteinsGate_FA_Patch_v1.0.exe (Inno Setup installer)
or: patch.xdelta (xdelta diff format)
"""

import json
import hashlib
import subprocess
from pathlib import Path
from dataclasses import dataclass, field
from typing import List, Dict, Tuple, Optional


@dataclass
class PatchFile:
    """A single file to include in the patch."""
    source_path: str  # Path to modified file
    target_path: str  # Where it goes in the game directory
    original_hash: str = ""  # SHA-256 of original file (for verification)
    modified_hash: str = ""  # SHA-256 of modified file
    size: int = 0


@dataclass
class PatchManifest:
    """Manifest of all files in the patch."""
    version: str = "1.0.0"
    game_version: str = "Steam HD / GOG"
    files: List[PatchFile] = field(default_factory=list)
    created_date: str = ""
    description: str = "Steins;Gate Persian Fan Translation Patch"


def compute_sha256(file_path: Path) -> str:
    """Compute SHA-256 hash of a file."""
    h = hashlib.sha256()
    with open(file_path, "rb") as f:
        while chunk := f.read(8192):
            h.update(chunk)
    return h.hexdigest()


def build_file_list(
    modified_dir: str,
    original_dir: str,
    game_root: str = "D:/Games/STEINSGATE",
) -> List[PatchFile]:
    """Build list of files that differ between original and modified.
    
    Args:
        modified_dir: Directory with modified (translated) files
        original_dir: Directory with original (clean) files
        game_root: Game installation path (for target_path)
    
    Returns:
        List of PatchFile for all changed files
    """
    modified = Path(modified_dir)
    original = Path(original_dir)
    files = []
    
    for mod_file in modified.rglob("*"):
        if mod_file.is_dir():
            continue
        
        rel_path = mod_file.relative_to(modified)
        orig_file = original / rel_path
        
        # Compute hash of modified file
        mod_hash = compute_sha256(mod_file)
        mod_size = mod_file.stat().st_size
        
        # Compare with original
        orig_hash = ""
        if orig_file.exists():
            orig_hash = compute_sha256(orig_file)
        
        # Only include if different from original (or new file)
        if mod_hash != orig_hash:
            files.append(PatchFile(
                source_path=str(mod_file),
                target_path=str(Path(game_root) / rel_path).replace("\\", "/"),
                original_hash=orig_hash,
                modified_hash=mod_hash,
                size=mod_size,
            ))
    
    return files


def generate_manifest(
    files: List[PatchFile],
    version: str = "1.0.0",
) -> PatchManifest:
    """Generate patch manifest."""
    from datetime import datetime
    return PatchManifest(
        version=version,
        files=files,
        created_date=datetime.utcnow().isoformat() + "Z",
    )


def save_manifest(manifest: PatchManifest, path: str = "patch_manifest.json"):
    """Save manifest to JSON."""
    data = {
        "version": manifest.version,
        "game_version": manifest.game_version,
        "created_date": manifest.created_date,
        "description": manifest.description,
        "file_count": len(manifest.files),
        "files": [
            {
                "source": f.source_path,
                "target": f.target_path,
                "original_hash": f.original_hash,
                "modified_hash": f.modified_hash,
                "size": f.size,
            }
            for f in manifest.files
        ],
    }
    Path(path).write_text(
        json.dumps(data, indent=2, ensure_ascii=False),
        encoding="utf-8",
    )
    print(f"Manifest saved: {path} ({len(manifest.files)} files)")


def generate_inno_setup_script(
    manifest: PatchManifest,
    output_path: str = "installer.iss",
) -> None:
    """Generate Inno Setup script for the patch installer.
    
    This creates a .iss file that can be compiled with Inno Setup
    to produce a self-extracting installer.
    """
    lines = [
        "; Steins;Gate Persian Fan Translation Patch Installer",
        "; Auto-generated by sgp-toolkit",
        "",
        "[Setup]",
        f'AppName=Steins;Gate Persian Translation Patch v{manifest.version}',
        "AppVersion=" + manifest.version,
        "AppPublisher=Steins;Gate FA Project Team",
        "DefaultDirName={pf}\\STEINS;GATE",
        "DefaultGroupName=Steins;Gate Persian Patch",
        "Compression=lzma2",
        "SolidCompression=yes",
        "LicenseFile=LICENSE.txt",
        "",
        "[Files]",
    ]
    
    for f in manifest.files:
        lines.append(f'Source: "{f.source_path}"; DestDir: "{{app}}\\{Path(f.target_path).parent}"; Flags: ignoreversion')
    
    lines.extend([
        "",
        "[Run]",
        "; Post-install verification",
        'Filename: "{app}\\patch_verify.exe"; Parameters: "--check"; StatusMsg: "Verifying patch..."; Flags: postinstall',
        "",
        "[Languages]",
        "Name: \"fa\"; MessagesFile: \"compiler:Languages\\Farsi.isl\"",
        "",
        "[CustomMessages]",
        "fa.Welcome=به نصب‌کننده پچ فارسی استینز؛گیت خوش آمدید",
        "fa.SelectDir=پوشه نصب بازی STEINS;GATE را انتخاب کنید",
    ])
    
    Path(output_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"Inno Setup script saved: {output_path}")


if __name__ == "__main__":
    import sys
    
    if len(sys.argv) < 3:
        print("Usage: build_patch.py <modified_dir> <original_dir> [version]")
        sys.exit(1)
    
    modified = sys.argv[1]
    original = sys.argv[2]
    version = sys.argv[3] if len(sys.argv) > 3 else "1.0.0"
    
    print("Building patch file list...")
    files = build_file_list(modified, original)
    print(f"Found {len(files)} changed files")
    
    manifest = generate_manifest(files, version)
    save_manifest(manifest)
    generate_inno_setup_script(manifest)
    
    print(f"\nPatch v{version} ready for packaging.")
